### ISSUE TITLE
Revisar tags de categorías

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#1]
Para la colección modelos: opciones válidas

**Comment by danflop** [comment]
@elkalexno @heleolaya @gonzalezivan90 @erikasv Durante la reunión del día viernes 1 de febrero de 2019 se acordó que se mantendrían los mismos tags de categorías: modelStatus, Published y thresholdType. Adicionalmente se agregarán nuevos tags (modelSeason, modelOrigin, modelGeoExtent, modelEpoch) que permitirán tener nuevas categorías en los filtros de la galería, y se discutirá utilizarlos en el buscador avanzado de especies.
