### ISSUE TITLE
Revisión colección 'models'

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#10]

**Comment by danflop** [comment]
Tarea duplicada en #4

**Comment by uamoreno** [comment]
Se realizó en producción la creación de los 41 nuevos atributos que se definieron en el diccionario V3: [Link al diccionario](https://docs.google.com/spreadsheets/d/1rC1XD5kQL1b8_z3i0t0HGUxjMTbbuNli-IIiP2rajkw/edit#gid=104259142).
