### ISSUE TITLE
Documentar el curso de acción para especies que cambian de nombre

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#104]
# Descripción

1. Decidir dónde documentar
2. Documentar lo que se debe hacer cuando una especie cambia de nombre, ya hay un caso en el que ocurrió (preguntar a Cristian, o si Camilo tiene el enlace porfa ponerlo aquí, yo ya lo perdí)

Cité a una reunión el lunes en la tarde para hablar de este tema, es importante hacerlo pronto porque Luis está esperando instrucciones para un caso nuevo.

# Resultado

Documento donde se describe qué se debe hacer cuando se presenten estos casos

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/104?planning-poker) with Zenhub @danflop @cazapatamar

**Comment by cazapatamar** [comment]
Se crear un [documento](https://docs.google.com/document/d/1omleCY8CP1DF4L5_BQMWCxnUGv8-2rOcxCLcbDGcVg8/edit) para manejar todos estos casos especiales en la carga de registros y se envia correo a equipo biomodelos
