### ISSUE TITLE
Pasos previos a carga de modelos y registros

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#105]
# Descripción

Hablar con Luis y preparar la base de datos y el sistema para la carga de registros yd e modelos.

1. Revisar la documentación existente sobre los procesos (drive, gitlab).
1. Discutir con Luis cómo ha sido el proceso que ha hecho con Camilo y complementar la documentación con lo que haga falta
1. Hacer las preparaciones para cada proceso (actualizar base de datos de pruebas con la de producción).

# Resultado
La siguiente semana se puede realizar el proceso de carga de modelos y registros

**Comment by Trjegul84** [comment]
Junto a Luis se revisaron los pasos previos a la carga de modelos. Se analizaron los pasos iniciales y se empezó el proceso para carga de modelos de peces. Como resultado de este ejercicio se documenta los pasos para [Flujo de carga de Modelos](https://docs.google.com/document/d/1K6zB5hn3OiTq7z1F9Qs46BaMjm5HMrjtNgyX0D9Tpl0/edit?usp=sharing) .
Queda pendiente documentar los pasos adicionales necesarios en el caso en que el ambiente de pruebas no se observan los modelos probablemente porque no cuenta con los datos de la base de datos SQL de producción y por lo tanto las especies, grupos y expertos no están asociados.

**Comment by erikasv** [comment]
Gracias @Trjegul84 , moví el archivo a la carpeta "Carga de datos" y le cambié el nombre para diferenciarlo del flujo de GeoServer
