### ISSUE TITLE
Ajustar datos para especie repetida Cheracebus lucifer

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-scrum#107]
La especie Cheracebus lucifer parece estar duplicada en la coleccion species por lo que se hace necesario hacer una revisión con el equipo temático para determinar si si es un duplicado y cual dejar de forma definitiva.

Los taxIDs son: 7012 y 7073

- Crear un csv de las colecciones species, models y records, enviarla al equipo temático 
- De acuerdo a lo que diga el equipo temático borrar una de las especies (la que se determine que es repetida)
- Ajustar los registros asociados a la especie borrada de acuerdo a lo que diga el equipo temático. Ya sea borrar los registros o pasarlos a la especie que se decidió dejar.

db.species.find({taxID: {$in : [
    7012, 7073
]}});

db.models.find({taxID: {$in : [
    7012, 7073
]}});

db.records.find({taxID: {$in : [
    7012, 7073
]}});

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/107?planning-poker) with Zenhub @danflop @erikasv @ManuelStardust @Trjegul84

**Comment by danflop** [comment]
Después de hacer una revisión de las especies y los modelos, se detectó que la especie con taxID 7012 tiene modelos asociados y pertenece a uno de los grupos de expertos. La especie 7073 no tiene modelos ni grupos asociados. En cuanto a registros se obtuvo el .csv y se envió al equipo temático para que revisen y tomen la decisión sobre el paso a seguir.

**Comment by danflop** [comment]
Como se acordó con el equipo temático, se unificaron los registros de ambas especies bajo el taxID 7012. De igual manera se dejó sólo un documento para esta especie.
