### ISSUE TITLE
[Spike] Revisar raster vs postgis

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#11]

**Comment by uamoreno** [comment]
Se han recibido de @elkalexno los archivos necesarios para ejecutar las pruebas y validaciones.

**Comment by uamoreno** [comment]
Se han llevado a cabo diferentes pruebas con los archivos facilitados por @elkalexno  dónde se identificó que se deben realizar ajustes al proceso de generación de tif, ya que estos no se pueden cargar en GeoServer en la opción:
![imagen](https://user-images.githubusercontent.com/26173177/53344420-a6931e80-38e0-11e9-88e4-7f6fc6baea35.png)
Para conseguir que se cargaran se ejecutó en línea de comandos la siguiente instrucción:
`>gdal_translate C_centralis_bin.tif C_centralis_bin_fix.tif`
Luego el archivo corregido se pudo cargar y representar desde GeoServer y QGIS cómo WCS.
Se sigue trabajando para almacenar la capa tif en la base de datos PostGIS y su configuración en GeoServer.

**Comment by uamoreno** [comment]
En las reuniones anteriores se había definido que se emplearía unicamente los archivos raster directamente desde el sistema de archivos.
La posibilidad de grabarlos y consularlos desde la base de datos se seguirá explorando más adelante.
