### ISSUE TITLE
Carga de registros de escarabajos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#110]
# Descripción y Resultados

Después de que finalizó la carga de modelos de plantas del jardín botánico, Luis inició la carga de registros de escarabajos a la base de datos de pruebas, nos informa que los registros quedaron cargados en esta, aunque no se pudieron crear 2 especies (ante esto no podemos hacer nada, pues las validaciones por las que falla la creación es al nivel del script de ellos).

Se debe finalizar el proceso de carga de estos registros para que queden en la base de datos de producción.

**Al finalizar este proceso actualizar la documentación del mismo en el gitlab**

# Consideraciones

- Revisar que la cantidad de registros cargados corresponda a la diferencia entre producción y pruebas, pues paso bastante tiempo desde que se sincronizaron. En caso de que no coincidan, se debe hacer la comparación con una restauración del backup de producción en el ambiente local (en pruebas no se cargan algunos registros por temas de validaciones de mongo creadas después de que esos registros existieran). Si aún así no coinciden, se debe discutir en el equipo para hablar con Luis porque es posible que expertos hayan cargado registros manualmente o algún otro evento haya ocurrido
- Leer la documentación del drive y del gitlab para entenderlos siguientes pasos del proceso. Resolver dudas al respecto con Camilo y Erika

**Comment by ManuelStardust** [comment]
- Se realizo la carga y validación de 5081 registros
- Se registraron 45 especies nuevas
- Se hizo corrección manual de casos especiales por sinonimia
