### ISSUE TITLE
Spike: Analizar cómo almacenar mapas de riqueza en GeoServer

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#111]
# Descripción y resultado

Como parte de los resultados del proyecto NatGeo se requiere disponer un servicio para consumir los mapas de riqueza. Se desea que esto se haga utilizando el GeoServer que ya se tiene para BioModelos. Estos mapas se consumirían de forma diferente a los mapas de los modelos que ya se tienen ahí y seguramente requerirán estilos diferentes también.

Determinar cómo se podrían almacenar estos mapas en conjunto con los que ya están ahí y que no haya inconveniente entre ellos (conservando la estructura actual). O dar un listado de los cambios que se requerirían en todos los sistemas para adaptarlos a un cambio de estructura.

# Consideraciones

La estructura que se maneja actualmente es que cada especie tiene su propio datastore

**Comment by cazapatamar** [comment]
Para almacenar estos nuevos datos se suguiere:

- Crear un nuevo workspace que se puede llamar `Mapas de riqueza` o `NatGeo`
- Dentro de este workspace crear un `data store` para cada archivo nuevo (raster, shape u otro formato)
- Crear una capa por cada `data store` creado y configurarla para exponer el servicio. En este paso es importante revisar si los estilos actuales funcionan para el tipo de capas que se desean subir o si se crean unos nuevos. Se recomienda crear nuevos estilos y así no afectar los de biomodelos.

Queda pendiente y se trabajará en otra tarea, todo lo relacionado con los permisos y el acceso de estas capas sin afectar los privilegos de los servicios actuales de biomodelos.
