### ISSUE TITLE
Elaborar propuesta para seguimiento de procesos de carga de BioModelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#112]
# Descripción y resultado

Crear las hojas discutidas en el documento [Plan_trabajo_Biomodelos_2023](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=1378242910) con la estructura deseada para documentar los pasos en cada proceso y evidenciar el seguimiento de cada uno.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/112?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Se propone el siguiente esquema:

https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995
