### ISSUE TITLE
Generar updates para arreglar datos de records

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-scrum#115]
Revisar caso nulos

**Comment by cazapatamar** [comment]
Se generan los updates para la mayoria de los casos.

Solo queda pendiente los que faltan por revisar por parte del equipo temático (Color amarillo y rojo).

**Comment by cazapatamar** [comment]
Luego de la revisión del equipo temático, se generan los updates restantes. Solo quedan faltando 3 casos los cuales se van a trabajar en una tarea posterior:

- Fila 27: `updated: Parameter "obj" to Document() must be an object` (1095)
- FIla 46: `acceptedNameUsage: Path `acceptedNameUsage` is required` (60)
- FIla 47: `taxID: Path `taxID` is required` (60)

**Comment by erikasv** [comment]
Ya se resolvió el de la fila 27, comentaré con la tarea de los otros 2 cuando se cree

**Comment by erikasv** [comment]
Tarea #119 creada para corregir los otros 2 campos.
