### ISSUE TITLE
Modificar campo para ruta en modelo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#12]

**Comment by uamoreno** [comment]
En el script de creación de nuevos campos para la colección models, se incluyó un atributo llamado: wms, allí se espera ubicar la ruta al aplicativo geoserver que se instalará para hospedar y servir las capas de información geográficas para los modelos regionalizados de distribución de especies.

**Comment by uamoreno** [comment]
Se debe emplear el atributo wms de la colección model:
![imagen](https://user-images.githubusercontent.com/26173177/59362659-76d61e00-8cf9-11e9-9799-3304f2b29140.png)

**Comment by erikasv** [comment]
Esto se realizó en alguna otra tarea.
