### ISSUE TITLE
[Spike] Revisar privilegios y permisos en GeoServer para capas de riqueza

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/biomodelos-scrum#120]

**Comment by cazapatamar** [comment]
Geoserver permite establecer permisos y definir reglas de acceso a los datos almacenados. De esta forma se pueden asignar un workspace (con sus data stores y capas) para que solo pueda ser consultado o editado por un usuario particular al cual se le puede establecer una contraseña de acceso. Estas reglas se definen en la sección de `Seguridad`, en la opcion `Nueva regla de acceso a datos`.

De esta forma, para el proyecto de natgeo y relacionado con el comentario anterior, se sugiere crear un usuario llamado `natgeo`, setear un clave y asociar una nueva regla de acceso donde se establezca que el unico usuario que tiene acceso a las capas de este worksapce es `natgeo`.

Lo anterior permite que las capas de este proyecto queden separadas del esquema actual de biomodelos y que el acceso únicamente se haga atraves del usuario creado `natgeo`.

Se intentó hacer una prueba pero por medio de la interfaz no se pudo crear un usuario de prueba ya que sparecia el siguiente error, lo cual parece indicar que el archivo xml de usuarios está bloqueado.

`Ha ocurrido un error al guardar el usuario: Already locked location: security/usergroup/default/users.xml.lock....`
