### ISSUE TITLE
Resolver temas pendientes para el cambio de permisos en las capas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#126]
# Descripción y resultado

Esta tarea es continuación de la tarea #125

1. Determinar la forma de actualizar todas las capas para que ya no sean públicas.
2. Encontrar y documentar cómo asignar los permisos para las capas nuevas

# Consideraciones

- Son muchas capas, así que hacer la actualización manualmente a través de la interfaz no es una opción
- Hay un problema con el endpoint probado para crear las reglas, puede ser que esté mal o que el body sea diferente, se recomienda explorar el repositorio [geoserver-rest](https://github.com/erikasv/geoserver-rest)
- En caso de que no se pueda cubrir todas las capas con una sola regla, se deberá hacer un script para actualizarlas una a una

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/126?planning-poker) with Zenhub @erikasv @ManuelStardust
