### ISSUE TITLE
Definir nombres de almacén en G.S.

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#13]
Y de capas Raster 'models'

**Comment by uamoreno** [comment]
Se analizaron tres escenarios: 

1. Establecer un area de trabajo de geoserver para almacenar todos los modelos Ej: 'Models' y almacenar en esta las capas raster en formato tif correspondientes a todos los modelos. 

2. Establecer areas de trabajo en geoserver teniendo en cuenta los grupos en el atributo modelID de la colección models y tomar únicamente la parte entera de dicho atributo para nombrar las capas raster que estarían almacenadas en cada almacen.

3. Generar espacios de trabajo para cada especie, y cargar en cada uno los modelos correspondientes, nombrando cada capa con el valor del atributo modelID tal y c{omo está en la colección.

Esta última opción permite tener un control adicional para relacionar los mapas a exponer en el visor y en el servicio, cruzando el valor del taxid, que sería el nombre del espacio de trabajo P.Ej taxid_7026  con sus modelos correspondientes: HER-5, HER-6. Empleando los metadatos que ofrece geoserver se almacenará en el campo Titulo, el nombre del archivo tif.

Adicionalmente puede resultar de utilidad emplear el API rest que expone geoserver para consultar los espacios de trabajo existentes: P.ej: http://192.168.205.192:8282/geoserver/rest/workspaces.json

Retornaría la siguiente salida:

![imagen](https://user-images.githubusercontent.com/26173177/55436619-69b2eb00-5562-11e9-8ac2-33d13adf14b4.png)

Para desarrollar esta configuración se hace necesario preparar las carpetas y archivos tif dentro del volumen pendiente en la tarea #14. La tarea de configuración corresponde a #17

**Comment by uamoreno** [comment]
La tarea está realacionada también con la actividad #16 ya que en ella se describe cual es el script que se debe emplear para generar los directorios físicos en el servidor para almacenar las diferentes capas tif, corregidas mediante el utilitario gdal_translate. El estandar definido aquí para nombrar los espacios de trabajo (workspace) también se emplea en dicho script, en el paso 3.

**Comment by uamoreno** [comment]
Se ha ajustado el script: Escribe rutas para modelos desde mongo.js para generar los nombres de la forma: 00001, 000234, etc... para las especies teniendo en cuenta que geoserver realiza una búsqueda por compración de cadenas de texto, y que no se tendrán mas de 99999 especies.
