### ISSUE TITLE
Revisar cómo se está realizando el cambio de estado de modelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#134]
# Descripción y resultado

En teoría los modelos cambian el `modelStatus` de *PendingValidation* a *Valid* cuando tienen una calificación de 3 o mayor.

Verificar si hay alguna lógica en el código que haga este cambio automáticamente.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/134?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Al revisar en el codigo de biomodelos buscando donde se cambian los modelos a estado validado, se busca por "Valid" solo se identifican cosas relaciondas con consultas y queries mas no inserts o updates tanto en el front como en el api. 

Adicional a eso, se revisó la documentacion funcional para entender un poco mejor el proceso y se encontró que probablemente el modelo cambia a valido una vez el moderador de un grupo aprueba una tarea del tipo "Modelo aprobado" asignada a algun experto. En el ambiente de pruebas se hizo toda la prueba: me asocié a un grupo que tuviera modelos por revisar (pendingValidation), con el moderador de un grupo me asigné una tarea de tipo "Modelo aprobado", lo califiqué con 5 estrellas y luego con el moderador aprobé la tarea. Finalmente el estado del modelo no cambió.
