### ISSUE TITLE
Borrar modelos basura

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#135]
# Descripción y resultado

Borrar de la base de datos de mongo todos los modelos que no tienen taxID o que el taxID está en `null` o en `'null'`

Primero se debe sincronizar la base de datos de pruebas con la de producción y ejecutar los comandos primero en la base de datos de pruebas, después replicar en producción.

Verificar también que no hayan colecciones temporales ni en producción ni en pruebas. En caso de que hayan consultar con Camilo que fue el encargado de la última carga.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/135?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Se borraron 274 modelos que cumplian las condiciones
