### ISSUE TITLE
Levantar ambiente local

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#137]
# Descripción y resultado

Levantar en ambiente local BioModelos, seguir las instrucciones de los componentes en GitHub: [api](https://github.com/PEM-Humboldt/biomodelos-api) y [website](https://github.com/PEM-Humboldt/biomodelos-website) y de GitLab: [Biomodelos](http://192.168.11.78/pem/biomodelos)

# Consideracioens
Al igual que con BioTablero, no levantar las bases de datos, sino usar las de pruebas en el datacenter

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/137?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by hacheG** [comment]
existe un problema al correr: bundle install, se generan una serie de errores relacionados con las gemas sass y pg, que derivan en un error (Psych::SyntaxError), se considera que hay un problema con el SO (Debian 12) como una posibilidad y tambien se evalua la posibilidad de hacer una actualizacion de ruby

**Comment by erikasv** [comment]
Se cierra esta tarea por priorizaciones. Cuando se vuelva a requerir que Hache levante este ambiente puede que hayan cambiaron algunas versiones
