### ISSUE TITLE
Solicitar recursos de servidor

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#14]

**Comment by uamoreno** [comment]
Se definió en reunión del enfoque que el servidor para instalar el aplicativo sería 192.168.11.42.
Se debe solicitar el mapeo de una carpetsa para los archivos de datos del geoserver en el volumen de red del 192.168.11.113.

**Comment by uamoreno** [comment]
Mediante una conversación telefónica @danflop requirió el montaje de una carpeta en el volumen de red del 192.168.11.113, se solicitó 200GB de espacio.
Estamos a la espera de la asignación de dichos recursos.
