### ISSUE TITLE
Revisar datos de Atlántico para integridad

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#141]
# Descripción y resultado
Extraer directamente de la base de datos de integridad la información relacionada con Atlántico. Si no hay información relacionada comentarlo en la tarea de [trello](https://trello.com/c/e0a5kdPo/28-para-el-%C3%A1rea-de-consulta-de-atl%C3%A1ntico-no-me-est%C3%A1-saliendo-la-informaci%C3%B3n-de-integridad-lo-busqu%C3%A9-en-dos-computadores-diferentes)

Si sí hay información, verificar por qué el backend no está trayendo la información

# Consideraciones

Verificar por el id del departamento tanto como número como string, puede ser que el problema esté relacionado con eso

En caso de que sea el tema del tipo del dato para el id, verifica también Antioquia que era el otro que presentó el mismo problema en algún momento

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/141?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
No existen datos para atlantico. Se deja comentario en trello
