### ISSUE TITLE
Carga de modelos de nivel 1 de carnivoros al geoserver

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#142]
Fila 20 [id 19](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995) del documento de plan_trabajo

# Consideraciones
- Tener actualizado el ambiente de pruebas
- Revisar el espacio en el servidor del GeoServer

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/142?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Se culmina la carga de modelos y se borran backups
