### ISSUE TITLE
Carga modelos geoserver: carnivoros y aves endémicas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#143]
- Carnívoros Nivel 2: Fila 21 [id 20](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995) del documento de plan de trabajo
- Aves Nivel 1: Fila 22 [id 21](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995) del documento de plan de trabajo

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/143?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Carga completa de los modelos.

Se presetó problema con el taxID nuevo 9732 (nueva especie) ya que el workspace en geoserver quedaba mal creado usando bmdbutils. Se creó manualmente el worspace y se ejecuto nuevamente bmdbutils upsert y funcionó.
