### ISSUE TITLE
Carga de modelos nivel 2 para aves endémicas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#146]
Carga en geoserver

[Filas 25](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995&range=25:25)

**Comment by cazapatamar** [comment]
Se realizan los backups.

No se comṕletó la carga durante la semana del 1 de noviembre ya que los metadatos de los modelos no estaban completos. Quedamos a la espera de la confirmacion de Carlos Jair para retomar la carga.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/146?planning-poker) with Zenhub @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Se termina la carga de modelos y queda listo para trabajo del atlas
