### ISSUE TITLE
Instalación y configuración de GeoServer

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#15]

**Comment by uamoreno** [comment]
Se ha instalado un contenedor docker con la imagen del geoserver institucional expuesto como microservicio en 192.168.11.82 Mediante la copia y carga de la imagen:

REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
docker.sibcolombia.net/geoserver   2.11.2              8c9309d07434        22 months ago       911MB

Creando un contenedor así:

docker run --name geoserver_bm -v /mnt/data/geoserver_bm:/opt/geoserver/data_dir -p 8181:8080 -d docker.sibcolombia.net/geoserver:2.11.2

Se modificó la contranseña por defecto de geoserver.
