### ISSUE TITLE
Pre release

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#155]
# Descripción
Crear la rama release en los repositorios del api y del website.

Actualizar la versión de ambos proyectos donde sea necesario.

Aplicar los cambios pequeños reportados en el trello.

Actualizar el ambiente de pruebas con lo esta rama release (website en el 42, api en el 105)

Al finalizar la actualización en el ambiente de pruebas agregar una sección con la documentación necesaria en el gitlab

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/155?planning-poker) with Zenhub @cazapatamar @erikasv @ManuelStardust

**Comment by erikasv** [comment]
El api de pruebas no está en el 105

**Comment by ManuelStardust** [comment]
Al montar el contenedor del front pueden aparecer algunos errores para la ejecución de Javascript que se resuelven quitando el compresor de Javascript: [Rails 5 -> 6 Upgrade: ES6 Uglifier bug
](https://www.mintbit.com/blog/rails-5-6-upgrade-es6-uglifier-bug).
