### ISSUE TITLE
Configurar servicios para disponer WCS o WMS

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#16]

**Comment by uamoreno** [comment]
Se ha generado un script para MongoDB, desde dónde se obtiene el valor de taxid,png,modelid y se escriben los comandos de linux necesarios para crear el directorio y copiar el archivo tif del modelo, a este script se le deben agregar lineas para llamar al api rest de geoserver para crear los espacios de trabajo y capas.

El script: Escribe rutas para modelos desde mongo.js
Se encuentra en la máquina Windows.

**Comment by uamoreno** [comment]
Se han realizado pruebas en la máquina virtual Centos de la consulta de mapas medianta el servicio WMS, que representa las capas de GeoServer cómo coverturas. 

Para avanzar en el objetivo de reemplazar los archivos png que representan los modelos se realizaron varias pruebas de carga de archivos tif y se definieron estilos SLD disponibles desde geoserver para represetar diferentses umbrales para u mismo tif.

Estilos generados:
![imagen](https://user-images.githubusercontent.com/26173177/55723748-6dfe5e80-59cf-11e9-9c7d-be83c8df75c4.png)

Es necesario incluir el llamado a la fución gdal_translate para corregir los archivos existentes ya que estos no se permiten cargar en GeoServer a menos que sean procesados antes por el utilitario indicado, y luego inclur las instrucciones de creación de espacios de trabajo y capas.

El llamado a la función se hace de la siguente manera, para estos tres ejemplos:
gdal_translate /media/sf_/root/Documents_windows/Mapas\ Varios/Aouts/Aotus\ vociferans_mx.tif aoutus_mx_fix.tif
gdal_translate /media/sf_/root/Documents_windows/Mapas\ Varios/Aouts/Aotus\ lemurinus_mx.tif a_lemunirus_mx_fix.tif
gdal_translate /media/sf_/root/Documents_windows/Mapas\ Varios/5094/Acacia\ decurrens_mx.tif a_decurrens_mx_fix.tif

**Comment by uamoreno** [comment]
Se modificó el paso 2 de script: Escribe rutas para modelos desde mongo.js, para que mediente la ejecución de la función gdal_translate se haga la copia del archivo tif corregido. Se asume que todos los archivos tif se encuentran ubicados en el mismo directorio.

Se debe validar la ubicación de dichos archivos.
Se debe validar con @heleolaya los mapas continuos y sus representaciones mediante umbrales.

**Comment by uamoreno** [comment]
Una vez revisados con Helena los mapas continuos y de umbral se llegó al entendimiento que los mapas de umbral son de presencia/ausencia, y no surgen de una representación del mapa contínuo sino del ejercicio de modelamiento de los records, luego estos representan cada uno un modelo diferente. Por lo cual se han conservado únicamente dos estilos: umbral_c y umbral_0, para ser empleados en la representación de los mapas.

**Comment by uamoreno** [comment]
Se cuenta con rutas actualizadas en la tarea #17
