### ISSUE TITLE
Actualización de modelos N1

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#162]
# Descripción

Actualización de modelos en imágenes N1. [Fila 31](https://docs.google.com/spreadsheets/d/1CA1QDvWTQ1ISd1gOaRT1tODl28Sp4KSGDrZeZTH_80c/edit#gid=2134248995) (id 32)

El paso 2 se modifica para no subir nada a mongo

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/162?planning-poker) with Zenhub @cazapatamar

**Comment by cazapatamar** [comment]
Se realiza la actualizacion de los modelos como imagenes y todo fue validado por Carlos en produccion
