### ISSUE TITLE
Actualización de modelos de carnivoros

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#168]
# Descripción

Es necesario actualizar un campo en todos los modelos de carnívoros. Laura envió a Camilo el csv con la relación de modelos y valores del campo correspondiente. 

Después de actualizar la colección de producción se debe volver a generar una copia (y eliminar la última generada, que fue del martes 16 de julio), por el proceso de carga que está iniciado

# Consideraciones

Se puede usar este [script](http://192.168.11.78/pem/biomodelos/blob/master/database/queries/update_model_by_id.js) de apoyo

**Comment by cazapatamar** [comment]
Se hace el ajuste de models de carnivoros y se genera backup de coleccion models
