### ISSUE TITLE
Cargar mapas regionalizados

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#17]

**Comment by uamoreno** [comment]
Se realizó un piloto de carga de los raster de 8 mapas de distribución de aves.
Se identificó que los nombres de los archivos raster a cargar no deben contener espacios, esto se solucionó al momento del put desde SFTP (put "archivo con espacios.tif" ../carpeta/archivo-con-espacios.tif). No se evidencia problema con el caracter _ (guión bajo) para las siguientes operaciones:

Se validó la generación de thumbnails mediante WMS:
http://192.168.11.58:8181/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=taxid-00090:AVE-513&styles=binario&bbox=-83.0,-14.0,-60.0,13.0&width=250&height=350&srs=EPSG:4326&format=image%2Fgif

Se validó la generación de zip descargable desde CSW mediante la operación DirectDownload:
http://192.168.11.58:8181/geoserver/ows?service=CSW&version=2.0.2&request=DirectDownload&resourceId=taxid-00090:AVE-513

Se validó la descarga de geotiff no comprimidos desde WCS mediante la operación GetCoverage:
http://192.168.11.58:8181/geoserver/wcs?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=taxid-00090:AVE-513&format=image/geotiff

Tareas asociadas #38 

@danflop
