### ISSUE TITLE
Revisión de problemas de registros en colecciones Species y Records

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#24]
Utilizar los backup de la base de datos para identificar los siguientes problemas:

- Especies que tienen registros de observación pero no tienen un registro en la colección species.
- Especies con taxID duplicado y acceptedNameUsage diferente.
- Conjunto de datos Murciélagos, Flora de Páramo y Mamíferos.

**Comment by uamoreno** [comment]
Se realizaron los ajustes correspondientes, se notificó mediante un correo electrónico los resultados, se tomó un backup de las colecciones species, records y models.
