### ISSUE TITLE
Modificación atributos en colección "records"

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#3]

**Comment by uamoreno** [comment]
Durante el primer sprint se logró extraer la información del arreglo reported a los nuevos atributos de la colección records. Junto con el cambio de nombres e inclusiones de los campos que se indican en el [Diccionario de datos V3](https://docs.google.com/spreadsheets/d/1rC1XD5kQL1b8_z3i0t0HGUxjMTbbuNli-IIiP2rajkw/edit#gid=104259142)

**Comment by uamoreno** [comment]
Se han codificado los scripts de mongo y R para realizar los ajustes requeridos, se hará una prueba final restaurando el último backup generado de la colección records.

**Comment by uamoreno** [comment]
Se realizó la prueba integrando tanto el backup del 15 de Febrero con el script en la consola de Mongo y el script de R sobre el cual se hicieron ajustes para llamar algunas librerías faltantes.
El resultado de la prueba fue exitoso para 1280 registros con arreglos. Los valores asociados a los arreglos reported, updated, created se movieron a los nuevos atributos del diccionaro propuesto por @heleolaya y @elkalexno.


![imagen](https://user-images.githubusercontent.com/26173177/53028279-8ffa4c80-3434-11e9-8772-9528a52966e5.png)


Se identifica un nuevo paso a realizar en producción cuando se lleve a cabo el proceso de migración final, ya que el esquema que valida los campos Mandatory contiene los atributos lon y lat que han cambiado de nombre y deben ser actualizado en el script Validation-scheme-Records.js

**Comment by uamoreno** [comment]
`# L L A M A D O   D E S D E    R
# source("/root/migra-records-reported.R")
#

library("mongolite")
library("textclean") # replace_curly_quote, replace_non_ascii
library("lubridate")
library("DescTools")
library("stringr")

m <- mongo("records", url = "mongodb://biomodelos:#F#W4ff4uV-7Kjmd@192.168.11.105:27016/produccion")

records <- m$find(query='{"reported":{"$ne":null}}',fields='{"reported.isOutlier_bm":true,"reported.oldTaxonomy_bm":true,"reported.inCaptivity_bm":true,"reported.otherIssues_bm":true,"reported.comments_bm":true,"reported.reportedDate":true,"reported.geoIssue_bm":true,"reported.idIssue_bm":true,"reported.userId_bm":true}',limit=400000)
j<-0
for(i in 1:nrow(records)){
  reportedArray<-records[i,"reported"]
  # V A R I A B L E S     C L E A N I N G
  id<-records[i,'_id']
  reportedOriginVagrant<-NULL
  reportedOldTaxonomyBm<-NULL
  reportedOriginIntroduced<-NULL
  reportedOtherIssuesBm<-NULL
  reportedCommentsBm<-NULL
  reportedDate<-NULL
  reportedGeoIssueBm<-NULL
  reportedIdIssueBm<-NULL
  reportedUserIdBm<-NULL
  # E X T R A E      V A L O R E S    D E L     A R R E G L O
  if(!is.null(reportedArray[[1]])){
    if(!is.null(nrow(reportedArray[[1]]))){  
      if(nrow(reportedArray[[1]])>0){
        j<-j+1
        # -------------------------------------------------- 
        if(!is.null(reportedArray[[1]]["isOutlier_bm"])){
          reportedOriginVagrant<-reportedArray[[1]]["isOutlier_bm"] 
          if(nrow(reportedOriginVagrant)>1){
            reportedOriginVagrant<-reportedOriginVagrant[nrow(reportedOriginVagrant),1]
          }
          if(reportedOriginVagrant=="FALSE"){
            reportedOriginVagrant="false"
          }else{
            if(reportedOriginVagrant=="TRUE"){
              reportedOriginVagrant="true"
            }
          }
        }
        # -------------------------------------------------- 
        if(!is.null(reportedArray[[1]]["oldTaxonomy_bm"])){
          reportedOldTaxonomyBm<-reportedArray[[1]]["oldTaxonomy_bm"]  
          if(nrow(reportedOldTaxonomyBm)>1){
            reportedOldTaxonomyBm<-reportedOldTaxonomyBm[nrow(reportedOldTaxonomyBm),1]
          }
          if(reportedOldTaxonomyBm=="FALSE"){
            reportedOldTaxonomyBm="false"
          }else{
            if(reportedOldTaxonomyBm=="TRUE"){
              reportedOldTaxonomyBm="true"
            }
          }
        }
        # --------------------------------------------------
        if(!is.null(reportedArray[[1]]["inCaptivity_bm"])){
          reportedOriginIntroduced<-reportedArray[[1]]["inCaptivity_bm"]  
          if(nrow(reportedOriginIntroduced)>1){
            reportedOriginIntroduced<-reportedOriginIntroduced[nrow(reportedOriginIntroduced),1]
          }
          if(reportedOriginIntroduced=="FALSE"){
            reportedOriginIntroduced="false"
          }else{
            if(reportedOriginIntroduced=="TRUE"){
              reportedOriginIntroduced="true"
            }
          }
        }
        # --- 
        if(!is.null(reportedArray[[1]]["otherIssues_bm"])){
          reportedOtherIssuesBm<-reportedArray[[1]]["otherIssues_bm"]  
          if(nrow(reportedOtherIssuesBm)>1){
            reportedOtherIssuesBm<-reportedOtherIssuesBm[nrow(reportedOtherIssuesBm),1]
          }
          if(reportedOtherIssuesBm=="FALSE"){
            reportedOtherIssuesBm="false"
          }else{
            if(reportedOtherIssuesBm=="TRUE"){
              reportedOtherIssuesBm="true"
            }
          }
        }
        # --- 
        if(!is.null(reportedArray[[1]]["geoIssue_bm"])){
          reportedGeoIssueBm<-reportedArray[[1]]["geoIssue_bm"]  
          if(nrow(reportedGeoIssueBm)>1){
            reportedGeoIssueBm<-reportedGeoIssueBm[nrow(reportedGeoIssueBm),1]
          }
          if(reportedGeoIssueBm=="FALSE"){
            reportedGeoIssueBm="false"
          }else{
            if(reportedGeoIssueBm=="TRUE"){
              reportedGeoIssueBm="true"
            }
          }
        }
        # --- 
        if(!is.null(reportedArray[[1]]["idIssue_bm"])){
          reportedIdIssueBm<-reportedArray[[1]]["idIssue_bm"]  
          if(nrow(reportedIdIssueBm)>1){
            reportedIdIssueBm<-reportedIdIssueBm[nrow(reportedIdIssueBm),1]
          }
          if(reportedIdIssueBm=="FALSE"){
            reportedIdIssueBm="false"
          }else{
            if(reportedIdIssueBm=="TRUE"){
              reportedIdIssueBm="true"
            }
          }
        }
      # --------------------------------------------------
        reportedCommentsBm<-tryCatch({reportedArray[[1]]["comments_bm"]},error=function(err){return(NULL)})
        if(!is.null(reportedCommentsBm)){
          if(nrow(reportedCommentsBm)>1){
            reportedCommentsBm<-reportedCommentsBm[nrow(reportedCommentsBm),1]
          } 
        }
        reportedCommentsBm<-gsub('\"', "", reportedCommentsBm)
        reportedCommentsBm<-replace_curly_quote(reportedCommentsBm)
        #------------------------------------------------------
        if(!is.null(reportedArray[[1]]["reportedDate"])){
          reportedDate<-reportedArray[[1]]["reportedDate"]
          if(nrow(reportedDate)>1){
            reportedDate<-reportedDate[nrow(reportedDate),1]
          }
        }
       # --------------------------------------------------
        reportedUserIdBm<-tryCatch({reportedArray[[1]]["userId_bm"]},error=function(err){return(NULL)})
        if(!is.null(reportedUserIdBm)){
          if(nrow(reportedUserIdBm)>1){
            reportedUserIdBm<-reportedUserIdBm[nrow(reportedUserIdBm),1]
          }
        }
        if(is.na(reportedUserIdBm)){
          reportedUserIdBm<-"null"
        }
        
        # --------------------------------------------------
        #print(paste("registros: ",j,id,reportedOriginVagrant,reportedOldTaxonomyBm,reportedOriginIntroduced,reportedOtherIssuesBm,reportedCommentsBm,reportedDate,reportedGeoIssueBm,reportedIdIssueBm,reportedOriginIntroduced,reportedUserIdBm,sep=' ')) 
        if(IsDate(reportedDate)){
          aux<-reportedDate;
          reportedDate<-paste0('{"$date":"',format(aux,format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
        }else{
          aux<-reportedDate;
          #reportedDate<-paste0('"',aux,'"')
          if(str_detect(aux,"[0-9]{2}/[0-9]{2}/[0-9]{4}")){
            reportedDate<-paste0('{"$date":"',format(strptime(aux,"%d/%m/%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{2}-[0-9]{2}-[0-9]{4}")){
            reportedDate<-paste0('{"$date":"',format(strptime(aux,"%d-%m-%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{10}")){
            reportedDate<-paste0('{"$date":"',format(as.POSIXct(as.double(aux),"%Y-%m",origin="1970-01-01"),format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
          }else{
            print(paste("REPORTED DATE NO EVALUADO AUN",j,id,sep=' ')) 
          }
        }
        print(paste("REPORTED",j,id,sep=' '))
        where<-paste('{"_id":{"$oid":"',id,'"}}',sep='')
        update<-paste('{"$set":{"reportedOriginVagrant":',reportedOriginVagrant,',"reportedOldTaxonomyBm":',reportedOldTaxonomyBm,',"reportedOriginIntroduced":',reportedOriginIntroduced,',"reportedOtherIssuesBm":',reportedOtherIssuesBm,',"reportedCommentsBm":"',reportedCommentsBm,'","reportedGeoIssueBm":',reportedGeoIssueBm,',"reportedIdIssueBm":',reportedIdIssueBm,',"reportedDate":',reportedDate,',"reportedUserIdBm":',reportedUserIdBm,'}}',sep='')
        m$update(where,update,multiple=FALSE)
      }
    }
  }
  i<-i+1
}

#
#   E X T R A Y E N D O    A R R E G L O      C R E A T E D
#
records <- m$find(query='{"created":{"$ne":null}}',fields='{"created.comments_bm":true,"created.citation_bm":true,"created.createdDate":true,"created.userId_bm":true}',limit=400000)
j<-0
for(i in 1:nrow(records)){
  createdArray<-records[i,"created"]
  # V A R I A B L E S     C L E A N I N G
  id<-records[i,'_id']
  createdCommentsBm<-""
  createdCitationBm<-""
  createdDate<-NULL
  createdUserIdBm<-NULL

  if(!is.null(createdArray[[1]])){
    if(!is.null(nrow(createdArray[[1]]))){  
      if(nrow(createdArray[[1]])>0){
        j<-j+1
        
        createdCommentsBm<-tryCatch({createdArray[[1]]["comments_bm"]},error=function(err){return("null")})
        createdCommentsBm<-gsub('\"', "", createdCommentsBm)
        createdCommentsBm<-replace_curly_quote(createdCommentsBm)
        createdCommentsBm<-replace_non_ascii(createdCommentsBm)
        createdCommentsBm<-paste0('"',createdCommentsBm,'"')
        if(createdCommentsBm=='"NA"' || createdCommentsBm=='"null"'){createdCommentsBm<-"null"}
        
        createdCitationBm<-tryCatch({createdArray[[1]]["citation_bm"]},error=function(err){return("null")})
        createdCitationBm<-gsub('\"', "", createdCitationBm)
        createdCitationBm<-replace_curly_quote(createdCitationBm)
        createdCitationBm<-replace_non_ascii(createdCitationBm)
        createdCitationBm<-paste0('"',createdCitationBm,'"')
        if(createdCitationBm=='"NA"' || createdCitationBm=='"null"'){createdCitationBm<-"null"}
        
        createdUserIdBm<-tryCatch({createdArray[[1]]["userId_bm"]},error=function(err){return(NULL)})
        if(!is.null(createdUserIdBm)){
          if(nrow(createdUserIdBm)>1){
            createdUserIdBm<-createdUserIdBm[nrow(createdUserIdBm),1]
          }
        }else{
          createdUserIdBm<-"null"
        }
        if(!is.null(createdArray[[1]]["createdDate"])){
          createdDate<-createdArray[[1]]["createdDate"]
          if(nrow(createdDate)>1){
            createdDate<-createdDate[nrow(createdDate),1]
          }
        }
        if(IsDate(createdDate)){
          aux<-createdDate;
          createdDate<-paste0('{"$date":"',format(aux,format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
        }else{
          aux<-createdDate;
          #reportedDate<-paste0('"',aux,'"')
          if(str_detect(aux,"[0-9]{2}/[0-9]{2}/[0-9]{4}")){
            createdDate<-paste0('{"$date":"',format(strptime(aux,"%d/%m/%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{2}-[0-9]{2}-[0-9]{4}")){
            createdDate<-paste0('{"$date":"',format(strptime(aux,"%d-%m-%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{10}")){
            createdDate<-paste0('{"$date":"',format(as.POSIXct(as.double(aux),"%Y-%m",origin="1970-01-01"),format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
          }else{
            if(nchar(createdDate)==0){
              createdDate='null';
            }else{
              print(paste("CREATED DATE NO EVALUADO AUN",createdDate,j,id,sep=' '))  
            }
          }
        }
        print(paste("CREATED",j,id,createdCommentsBm,createdCitationBm,createdUserIdBm,createdDate,sep=' '))
        where<-paste('{"_id":{"$oid":"',id,'"}}',sep='')
        update<-paste('{"$set":{"createdCommentsBm":',createdCommentsBm,',"createdCitationBm":',createdCitationBm,',"createdUserIdBm":',createdUserIdBm,',"createdDate":',createdDate,'}}',sep='')
        m$update(where,update,multiple=FALSE)
      }
    }
  }
  
  i<-i+1
}



#
#   E X T R A Y E N D O    A R R E G L O      U P D A T E D 
#
records <- m$find(query='{"updated":{"$ne":null}}',fields='{"_id":true,"updated.lat":true,"updated.lon":true,"updated.speciesOriginal":true,"updated.locality":true,"updated.userId_bm":true,"updated.updatedDate":true}',limit=400000)
j<-0
for(i in 1:nrow(records)){
  updatedArray<-records[i,"updated"]
  # V A R I A B L E S     C L E A N I N G
  id<-records[i,'_id']
  updatedLat<-NULL
  updatedLon<-NULL
  updatedAcceptedNameUsage<-NULL
  updatedLocality<-NULL
  updatedUserIdBm<-NULL
  updatedDate<-NULL

  #if(id=="599355dbfbac47018553d0a9"){
  #print(paste(i,id,is.null(updatedArray[[1]]),is.null(nrow(updatedArray[[1]])),nrow(updatedArray[[1]]),sep=' '))    
  #}

  if(!is.null(updatedArray[[1]])){
    if(!is.null(nrow(updatedArray[[1]]))){  
      if(nrow(updatedArray[[1]])>0){
        j<-j+1
        
        updatedLat<-tryCatch({updatedArray[[1]]["lat"]},error=function(err){return(NULL)})
        if(!is.null(updatedLat)){
          if(nrow(updatedLat)>1){
            updatedLat<-updatedLat[nrow(updatedLat),1] 
          }
        }
        if(is.na(updatedLat) || is.null(updatedLat)){
          updatedLat<-"null"
        }
        
        updatedLon<-tryCatch({updatedArray[[1]]["lon"]},error=function(err){return(NULL)})
        if(!is.null(updatedLon)){
          if(nrow(updatedLon)>1){
            updatedLon<-updatedLon[nrow(updatedLon),1] 
          } 
        }
        if(is.na(updatedLon) || is.null(updatedLon)){
          updatedLon<-"null"
        }
        
        updatedAcceptedNameUsage<-tryCatch({updatedArray[[1]]["speciesOriginal"]},error=function(err){return(NULL)})
        if(!is.null(updatedAcceptedNameUsage)){
          if(nrow(updatedAcceptedNameUsage)>1){
            updatedAcceptedNameUsage<-updatedAcceptedNameUsage[nrow(updatedAcceptedNameUsage),1] 
          } 
        }
        updatedAcceptedNameUsage<-gsub('\"', "", updatedAcceptedNameUsage)
        updatedAcceptedNameUsage<-replace_curly_quote(updatedAcceptedNameUsage)
        updatedAcceptedNameUsage<-replace_non_ascii(updatedAcceptedNameUsage)
        updatedAcceptedNameUsage<-paste0('"',updatedAcceptedNameUsage,'"')
        if(updatedAcceptedNameUsage=='"NA"' || updatedAcceptedNameUsage=='"null"'){updatedAcceptedNameUsage<-"null"}
        
        updatedLocality<-tryCatch({updatedArray[[1]]["locality"]},error=function(err){return(NULL)})
        if(!is.null(updatedLocality)){
          if(nrow(updatedLocality)>1){
            updatedLocality<-updatedLocality[nrow(updatedLocality),1] 
          } 
        }
        updatedLocality<-gsub('\"', "", updatedLocality)
        updatedLocality<-replace_curly_quote(updatedLocality)
        updatedLocality<-replace_non_ascii(updatedLocality)
        updatedLocality<-paste0('"',updatedLocality,'"')
        if(updatedLocality=='"NA"' || updatedLocality=='"null"'){updatedLocality<-"null"}
        
        updatedUserIdBm<-tryCatch({updatedArray[[1]]["userId_bm"]},error=function(err){return(NULL)})
        if(!is.null(updatedUserIdBm)){
          if(nrow(updatedUserIdBm)>1){
            updatedUserIdBm<-updatedUserIdBm[nrow(updatedUserIdBm),1]
          }
        }else{
          updatedUserIdBm<-"null"
        }
        
        if(!is.null(updatedArray[[1]]["updatedDate"])){
          updatedDate<-updatedArray[[1]]["updatedDate"]
          if(nrow(updatedDate)>1){
            updatedDate<-updatedDate[nrow(updatedDate),1]
          }
        }
        
        
        #print(paste("registros: ",j,id,reportedOriginVagrant,reportedOldTaxonomyBm,reportedOriginIntroduced,reportedOtherIssuesBm,reportedCommentsBm,reportedDate,reportedGeoIssueBm,reportedIdIssueBm,reportedOriginIntroduced,reportedUserIdBm,sep=' ')) 
        if(IsDate(updatedDate)){
          aux<-updatedDate;
          updatedDate<-paste0('{"$date":"',format(aux,format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
          #print(paste("OK DATE",j,id,format(aux,format='%Y-%m-%dT%H:%M:%S.0Z'),aux,sep=' ')) 
        }else{
          aux<-updatedDate;
          #reportedDate<-paste0('"',aux,'"')
          if(str_detect(aux,"[0-9]{2}/[0-9]{2}/[0-9]{4}")){
            #print(paste("OK STRING A DATE",j,id,format(strptime(aux,"%d/%m/%Y"),format='%Y-%m-%dT01:01:01.0Z'),strptime(aux,"%d/%m/%Y"),aux,sep=' ')) 
            updatedDate<-paste0('{"$date":"',format(strptime(aux,"%d/%m/%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{2}-[0-9]{2}-[0-9]{4}")){
            #print(paste("OK STRING A DATE",j,id,format(strptime(aux,"%d/%m/%Y"),format='%Y-%m-%dT01:01:01.0Z'),strptime(aux,"%d/%m/%Y"),aux,sep=' ')) 
            updatedDate<-paste0('{"$date":"',format(strptime(aux,"%d-%m-%Y"),format='%Y-%m-%dT01:01:01.0Z'),'"}')
          }else if(str_detect(aux,"[0-9]{10}")){
            #print(paste("PROBLEMA",j,id,createdDate,IsDate(createdDate),format(aux,format='%Y-%m-%dT%H:%M:%S.0Z'),sep=' ')) 
            updatedDate<-paste0('{"$date":"',format(as.POSIXct(as.double(aux),"%Y-%m",origin="1970-01-01"),format='%Y-%m-%dT%H:%M:%S.0Z'),'"}')
          }else{
            if(nchar(updatedDate)==0){
              updatedDate='null';
            }else{
              print(paste("UPDATED DATE NO EVALUADO AUN",updatedDate,j,id,sep=' '))  
            }
          }
        }
        print(paste("UPDATED",j,id,  updatedLat,updatedLon,updatedAcceptedNameUsage,updatedLocality,updatedUserIdBm,updatedDate,sep=' '))
        where<-paste('{"_id":{"$oid":"',id,'"}}',sep='')
        update<-paste('{"$set":{"updatedLat":',updatedLat,',"updatedLon":',updatedLon,',"updatedAcceptedNameUsage":',updatedAcceptedNameUsage,',"updatedLocality":',updatedLocality,',"updatedUserIdBm":',updatedUserIdBm,',"updatedDate":',updatedDate,'}}',sep='')
        m$update(where,update,multiple=FALSE)
      }
    }
  }
  i<-i+1
}`

**Comment by uamoreno** [comment]
Luego de terminada esta tarea se definió un nuevo ajuste sobre el arreglo updated, que será tratado en un issue para el siguiente sprint.
