### ISSUE TITLE
Consulta de especie en home

### ISSUE THREAD

**Issue by uamoreno** [PEM-Humboldt/biomodelos-scrum#30]
Revisar la consulta para la especie Saguinus leucopus, ya que al consultarla está presentando un comportamiento inusual.

**Comment by alegnaaived** [comment]
Empezamos explorando desde la línea [58](https://github.com/LBAB-Humboldt/BioModelos.v2/blob/973f6f513cf032380fb3de6e958e1109f3cc77ec/app/assets/javascripts/controllers/home_controller.js)

Se realizó el mapeo desde [Autocomplete](https://github.com/LBAB-Humboldt/BioModelos.v2/blob/973f6f513cf032380fb3de6e958e1109f3cc77ec/app/controllers/species_controller.rb), [controlador del home](https://github.com/LBAB-Humboldt/BioModelos.v2/blob/973f6f513cf032380fb3de6e958e1109f3cc77ec/app/assets/javascripts/controllers/home_controller.js) y la [vista del home](https://github.com/LBAB-Humboldt/BioModelos.v2/blob/973f6f513cf032380fb3de6e958e1109f3cc77ec/app/views/home/show.html.erb).

Es un filtro que no muestra todos los resultados de la consulta, y que al inspeccionar la página, si se visualiza que la respuesta llegó completa.

![Captura de pantalla de 2019-03-21 15-49-48.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/04bee6ea-e94b-4388-a252-b48ebbe4cd67)

**Comment by uamoreno** [comment]
db.species.find({species:/Sagu/}).sort({species:1}) arroja 5 resultados desde la BD, y no se evidencian caracteres especiales, adicionalmente la consulta por separado de cada uno de los 5 registros encontrados si está siendo mostrada en el autocomplete.
