### ISSUE TITLE
[Spike] Método de seguridad a implementar para abrir el API al público.

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#35]
Revisar los diferentes métodos que se podrían aplicar al API de BioModelos para algunos de sus endpoints a terceros.

**Comment by erikasv** [comment]
Más que métodos puntuales hay una serie de recomendaciones y prácticas que aplicar para asegurar un api al momento de hacerlo accesible por el público en general.

Debemos empezar aplicando los más importantes/urgentes de las siguientes listas:
* https://expressjs.com/en/advanced/best-practice-security.html
*  https://medium.com/@nodepractices/were-under-attack-23-node-js-security-best-practices-e33c146cb87d
