### ISSUE TITLE
Desarrollo de ETLs para operaciones comunes en la base de datos relacional de BioModelos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#36]
Por el momento se crearían los siguientes procesos de ETL para que los pueda manejar @heleolaya:

* Agregar especie a grupo. (Hay que tener en cuenta que una especie **sólo** puede pertenecer a un grupo).
* Cambiar valor de campo booleano is_admin para un usuario de grupo.

**Comment by uamoreno** [comment]
Se debe revisar que la instalacin de pentaho cuente con las libreras jar adecuadas para contecarse a la base de datos postgres.

**Comment by uamoreno** [comment]
Se construyeron ETLs en el equipo de @heleolaya  para cargar la información de groups_species y se creó el usuaro lba con permisos de consulta, escritura y modificación para la base de datos biomodelos_pro

**Comment by danflop** [comment]
- Agregar especie a grupo
