### ISSUE TITLE
Definir campos a mostrar en nueva caja registro y lógica en la edición.

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#37]
Realizar reunión donde queden definidos los campos que estarán en la caja de registro (edición y reporte) al igual que la lógica a seguir cuando se efectúe el proceso de edición de un registro.

**Comment by erikasv** [comment]
@danflop , @elkalexno , @heleolaya , @uamoreno 

Las conclusiones de la reunión fueron:
Para la caja de registro:
- [x] Quitar el id de la especie
- [x] Cargar toda la información de la taxonomía, ésta se saca de la especie
- [x] De la sección "Información del registro" quitar el campo "Creado por"
- [x] Mover los campos "Fuente", "ID registro original", "Fecha descarga fuente" después del campo "URL"
- [x] Eliminar los campos "Fecha inicial", "Fecha final" y "Fecha creación"
- [x] Poner el campo "Fecha interpretada" después de "Evidencia de registro" y cambiarle el nombre a "Fecha del registro"
- [x] Los valores del campo "En casco urbano" deberán ser "Sí" (true) y "No" (false)
- [x] Agregar tooltips para los campos en la sección "Calidad del registro"
- [x] En la sección de Ubicación, quitar los valores interpretados y el icono de consistente para los campos localidad y altitud.

Para la edición de un registro:
- [x] La edición del nombre aceptado está editando el atributo "speciesOriginal" de la base de datos, corregir el API y las peticiones del front, para que no se envíe el atributo "speciesOriginal" sino "acceptedNameUsage". El atributo "speciesOriginal" no es modificable
- [x] Cuando un registro ha sido reportado, el botón de edición y el de reportar el registro deben estar deshabilitado

En la creación de registros:
- [x] Cambiar los campos Departamento, Municipio y Tipo de registro por listas desplegables
- [x] Estandarizar los nombres de los campos del formulario de creación con los de la caja de registros.

**Comment by erikasv** [comment]
Se crearon las siguientes tareas para realizar los ajustes necesarios:

* [Cargar información de la especie al traer un registro](https://github.com/LBAB-Humboldt/biomodelos_db_api/issues/113)
* [Cargar la información correcta de cada registro en la nueva caja de registros](https://github.com/LBAB-Humboldt/BioModelos.v2/issues/148)
* [Modificaciones visuales en la información de un registro](https://github.com/LBAB-Humboldt/BioModelos.v2/issues/161)
* [Corregir campo de edición de un registro](https://github.com/LBAB-Humboldt/biomodelos_db_api/issues/114)
* [Corregir campo de edición de un registro](https://github.com/LBAB-Humboldt/BioModelos.v2/issues/162)
* [Deshabilitar botones de edición y reporte para registros reportados](https://github.com/LBAB-Humboldt/BioModelos.v2/issues/163)
* [Agregar tooltips para los campos en la sección "Calidad del registro"](https://github.com/LBAB-Humboldt/BioModelos.v2/issues/164)
