### ISSUE TITLE
Seleccionar tareas prioritarias a realizar para asegurar el API

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#39]
Teniendo en cuenta las recomendaciones de los enlaces mencionados en la tarea [[Spike] Método de seguridad a implementar para abrir el API al público.](https://app.zenhub.com/workspaces/biomodelos-5c5072b49eb374296d67bbca/issues/lbab-humboldt/biomodelos-scrum/35#issuecomment-502847864). Listar los más prioritarios / urgentes / importantes a implementar

**Comment by erikasv** [comment]
En el repositorio de gitlab se creó un archivo con las tareas priorizadas de uno de los dos enlaces citados en el spike

**Comment by erikasv** [comment]
El documento de gitlab se amplió con la información relevante de los dos enlaces resultado del spike. Adicionalmente se creó una epica con las tareas prioritarias a realizar, la idea es que a medida que se tenga el tiempo ir agregando las de más baja prioridad a la misma epica hasta terminarlas.
