### ISSUE TITLE
Subida y validación de registros de observación para modelatones de Julio y Agosto

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#41]

**Comment by uamoreno** [comment]
Se realizó la carga de 1226 registros de anfibios a producción

**Comment by uamoreno** [comment]
Se realizó ajustes y validaciones sobre registros de tortugas.
Se ajustó el script en R que carga los registros a pruebas.
Se validó los datos cargados con mongoose
