### ISSUE TITLE
Pentaho Cómo Servicio

### ISSUE THREAD

**Issue by uamoreno** [PEM-Humboldt/biomodelos-scrum#45]
Verificar de qué manera se puede configurar la herramienta de ETLs Pentaho Data Integrator cómo un servicio, para implementar de manera centralizada un prevalidador de los tipos de campos y campos enviados a los script de R

**Comment by erikasv** [comment]
@danflop creo que esto sería abarcado desde las herramientas que está desarrollando Marcelo? Podríamos cerrarla.

**Comment by danflop** [comment]
> @danflop creo que esto sería abarcado desde las herramientas que está desarrollando Marcelo? Podríamos cerrarla.

De acuerdo. Esto hace parte de las estrategias de automatización que se están desarrollando.
