### ISSUE TITLE
Deploy BioModelos Front-End

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#49]
Deploy BioModelos Front-End locally following the docs and using a Test API Backend already deployed.

**Comment by erikasv** [comment]
Please add your comments about documentation on this doc: https://docs.google.com/document/d/1NfwIeOikkgtj0ZfvorOdbBlLx9RgEyPBzfu12-Wm4iw/edit

**Comment by erikasv** [comment]
@alegnaaived  @cazapatamar  Cerraré este issue porque tengo entendido que uds ya desplegaron el proyecto en sus máquinas
