### ISSUE TITLE
Update API Backend docs

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#50]
Update API Backend documentation for deployment. 

Comments
[https://docs.google.com/document/d/1NfwIeOikkgtj0ZfvorOdbBlLx9RgEyPBzfu12-Wm4iw/edit?usp=sharing](https://docs.google.com/document/d/1NfwIeOikkgtj0ZfvorOdbBlLx9RgEyPBzfu12-Wm4iw/edit?usp=sharing)

**Comment by erikasv** [comment]
Se modificaron las instrucciones del gitlab para desplegar el api en el servidor. Las instrucciones genéricas van a ser agregadas al repositorio de github.

@alegnaaived, @cazapatamar, @danflop Por favor revisar estas nuevas instrucciones y actualizar los comentarios en este issue o en el documento.
