### ISSUE TITLE
Revisión de documentación y puesta en contexto de GeoServer para BioModelos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#59]
Reunión con Elkin para revisar el trabajo previo con Alejandro para subir los modelo

Identificar directorios donde se guardan los modelos

Identificar enlaces a los modelos (enlaces directos al thumbnail, mapa y descarga)

Revisar servicios WMS, WPS y WFS

Generar documento con restultados

**Comment by cazapatamar** [comment]
Prioridad ALTA

**Comment by cazapatamar** [comment]
Se genera este documento: https://docs.google.com/document/d/1XGewv3jcr-fJ6pGKCXjSFRA8SsLAA3hPLsozegfk2Pc/edit#heading=h.uf8yy0l86f7t

Se propone crear una nueva tarea en el proximo sprint para documentar mejor el flujo actual y posibles mejoras.

Se propone crear una tarea para la revisión de script con Elkin y analizar su uso y posibles mejoras
