### ISSUE TITLE
Quitar gateway del front

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#62]
Deshacer el cambio de la conexión que conecta al front con el gateway para la comunicación con el API interno. La conexión ahora sería directa.

Eliminar la credencial del frontend y la configuración de las rutas en el gateway.

**Comment by erikasv** [comment]
Para esta tarea:

1. Actualicé la documentación general de BioModelos en el [gitlab](http://192.168.11.78/pem/biomodelos)
1. Creé un PR en el front para quitar la configuración relacionada con el gateway
1. No es necesario cambiar la configuración del gateway, sólo remover las credenciales que tengan scope `all`, pues esta sería una opción por defecto si alguna vez queremos habilitar todos los endpoints para algo. Pero podemos eliminar la configuración completamente y que sólo se tenga acceso a los endpoints listados. @danflop @cazapatamar @alegnaaived @Trjegul84 Que opinan?

**Comment by cazapatamar** [comment]
De acuerdo a lo conversado ayer, estoy de acuerdo con sólo eliminar el user "front" y dejar el scope "all" por si luego necesitamos dar estos permisos para acceder a todos los endpoints

**Comment by erikasv** [comment]
Se desactivó tanto la aplicación del front como las credenciales que tenía asociadas
