### ISSUE TITLE
Subida nuevos registros

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#66]
Las especies a cargar son de tortugas, aves y el miquito del caquetá 
Encargado de BioModelos: Helena.

---

##### Actualización al 11-jun

Lo primero sería cómo corregir errores de validación del api.

Una aproximación de lo que queda pendiente:

1. Copiar los registros de producción a la colección de tortugas
1. Exportar registros de tortuga a csv para enviárselos a Helena
1. Helena devuelve el csv con los campos necesarios corregidos
1. Ejecutar el script de corrección de duplicados espaciales
1. Continuar el proceso de carga

**Comment by erikasv** [comment]
Se devuelve al backlog hasta nuevo aviso por parte del equipo temático

**Comment by alegnaaived** [comment]
Se creó la colección vacía "tortuga"
![image](https://user-images.githubusercontent.com/15584917/115459904-339a3f80-a1ed-11eb-9847-f92489e2a3fd.png)

**Comment by alegnaaived** [comment]
Helena quedó de subir a hoy los registros, pero aún no informa si ya están cargados. Preguntaré el martes de la próxima semana (27 de abril)

**Comment by alegnaaived** [comment]
Se preguntó y quedó de subir los registros hoy, pero aún no los ha subido. Es probable que esta tarea continúe la próxima semana.

**Comment by alegnaaived** [comment]
Le pregunté a Helena nuevamente vía chats, pero aún no me da respuesta

**Comment by alegnaaived** [comment]
Hoy Helena subió 730 registros:

![image](https://user-images.githubusercontent.com/15584917/118187858-2bf14380-b405-11eb-869e-a57afd7c3d97.png)

**Comment by alegnaaived** [comment]
> Hoy Helena subió 730 registros:
> 
> ![image](https://user-images.githubusercontent.com/15584917/118187858-2bf14380-b405-11eb-869e-a57afd7c3d97.png)

Al comentar esto en el Daily, se concluyó que hay que volver a crear la colección validada "tortuga" y pedir que queden los registros en la colección que creamos nosotros.

**Comment by alegnaaived** [comment]
Se creó nuevamente la colección "tortuga" y ya se pidió a Helena que vuelva a subir los registros.
![image](https://user-images.githubusercontent.com/15584917/119046165-fb1f8a00-b981-11eb-97d7-26033950ce5d.png)

**Comment by alegnaaived** [comment]
Step 3:
![image](https://user-images.githubusercontent.com/15584917/120816798-b44f9980-c516-11eb-8a08-0d7db75a2f4b.png)

Step 4 and 5 finished.

**Comment by alegnaaived** [comment]
Helena nos entregó dos archivos CSV con la validación del campo "spatialDuplicated" para los registros en la colección "produccion" y la colección "copy_tortuga" en el servidor de producción. Se identificó el listado de columnas con celdas sin valor (vacías) y que son obligatorias según el [diccionario de datos](https://docs.google.com/spreadsheets/d/1rC1XD5kQL1b8_z3i0t0HGUxjMTbbuNli-IIiP2rajkw/edit?usp=sharing):
- occurrenceID
- resourceName
- resourceFolder
- resourceIncorporationDate
- privateData

De los campos anteriores, se tiene el valor por defecto en el diccionario a excepción de occurrenceID.

Se le está consultando a Helena qué hacer en esos casos (para todos los campos obligatorios).

Dado este panorama, los siguientes pasos son:
 - Usar ese CSV para iniciar nuevamente todos los pasos
 - Eliminar los registros de producción antes de migrar los datos (en el último paso de la guía de [GitLab](http://192.168.11.78/pem/biomodelos/blob/master/database/new_records/README.md))

Por último, se ha actualizado el [README.md](http://192.168.11.78/pem/biomodelos/blob/master/database/new_records/README.md) con todas las instrucciones que se consideran que hacían falta y aquellas opciones que se pueden dar al cargar registros (como este caso poco frecuente).

**Comment by alegnaaived** [comment]
Quedaron cargados los registros. Le pedí a Helena el favor de ayudarme a revisar si sí quedaron bien.

**Comment by alegnaaived** [comment]
Helena revisó y quedó bien la carga.

**Comment by alegnaaived** [comment]
En el daily acordamos restaurar la colección records de producción a la base de datos de pruebas

**Comment by alegnaaived** [comment]
Se identificaron 7 registros que no se pudieron copiar de los taxID de producción que coinciden con el mismo listado de los taxID de la colección nueva en pruebas.

- Los taxID son: [ 7006.0,8453.0,1023.0,7046.0,7805.0,7802.0,7257.0,9209.0 ]
- Los _id de los elementos que no fueron copiados y que ya estaban el producción son:
  - ObjectId(58b6a887875e0e0f1c006d41)
  - ObjectId(58b6a88b875e0e0f1c006d42)
  - ObjectId(58b6a890875e0e0f1c006d43)
  - ObjectId(58b6a895875e0e0f1c006d44)
  - ObjectId(58b6a899875e0e0f1c006d45)
  - ObjectId(58b6a89e875e0e0f1c006d46)
  - ObjectId(58b6a8a3875e0e0f1c006d47)

**Comment by alegnaaived** [comment]
Se actualizó la colección records en pruebas y se eliminaron las colecciones temporales de pruebas. Se completó el paso 13 y último descrito en las instrucciones http://192.168.11.78/pem/biomodelos/blob/master/database/new_records/README.md
