### ISSUE TITLE
Revisión de consultas para filtros en búsqueda avanzada y estadísticas en el home

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#72]
# Descripción
Revisar, tanto desde Rails como desde el API (en los casos que aplique), si las consultas que se están realizando cumplen con las condiciones expuestas en cada caso:

- Filtro "con modelo" en búsqueda avanzada:
  Es un nuevo filtro que no está disponible en este momento en producción. Se debe verificar si se puede poner a funcionar con la lógica que hay actualmente para los demás filtros o que cambios requiere tanto en Rails como en el API.
- Estadísticas del home:
  Se desea saber si estas consultas (en el API) están retornando la información correctamente y cómo se podrían agregar otras categorías en el estado de los modelos

**Comment by erikasv** [comment]
Hallazgos:

Se quieren mostrar las siguientes categorías en las estadísticas del Home:

Validados (modelStatus = Valid) Sólo tener en cuenta 1 por especie y revisar tanto en nivel 1 como en nivel 2. _Ignorar las demás condiciones si cumple_
Publicado (published = true). _Ignorar las demás menos el caso 1_
En desarrollo (modelStatus = pendingValidation y published = false).
Estadístico (modelStatus = Developing).
Sin Modelo

En las estadísticas del home:
1. Solo se están teniendo en cuenta los modelos de nivel 1
2. Campo que se toma en cuenta: modelStatus (en desarrollo, pendiente de validación y válido). Para agregar los publicados habría que agregar la lógica para que tome en cuenta el campo "published" y que estén pendiente de validación.
3. Para agregar los del laboratorio se deberían tener en cuenta los que tengan modelStatus = Developing o también que en el campo Threshold = Continuous. 

Correcciones que hay que hacer:
1. Preguntar a Helena si los modelos de Ayerbe deberían tener estado "Validado"
2. Preguntar si podría darse un caso donde ingrese un modelo Continuo que no sea generado por el Laboratorio. Lo anterior para definir como identificar un modelo del laboratorio para estas cifras.

**Comment by danflop** [comment]
Filtro "con modelo" en búsqueda avanzada:

En este momento, la consulta [getAllSpecies](https://github.com/PEM-Humboldt/biomodelos_db_api/blob/develop/src/api/species/specie.controller.js#:~:text=export%20async%20function-,getAllSpecies,-(req%2C%20res)%20%7B) ya hace match con la colección models y el campo modelStatus. Teniendo eso en cuenta, para poder saber cuáles son las especies con al menos un modelo bastaría con que se obtuviera al menos un resultado de la colección models para una especie.

**Comment by erikasv** [comment]
A raíz de otra tarea se confirmó que sólo los modelos que produce el equipo de BioModelos pueden tener `thresholdType` Continuous
