### ISSUE TITLE
Habilitar política de Log en gateway

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#75]
Habilitar la política de log en el gateway: https://www.express-gateway.io/docs/policies/log/

**Comment by erikasv** [comment]
En este [MR](http://192.168.11.78/pem/biomodelos_gateway/merge_requests/10) se agrega la política con el mensaje correspondiente.

@cazapatamar y @danflop por favor revisarlo e indicarme si creen que así estaría bien o si faltaría algo por agregar al mensaje

**Comment by cazapatamar** [comment]
Yo creo que está bien. Ya puse mi manita arriba en el MR.
