### ISSUE TITLE
Subir los registros de murciélagos

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-scrum#80]
Tener en cuenta que el nuevo flujo de trabajo requiere ser actualizado a medida que se realiza cada paso.

**Comment by alegnaaived** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/80?planning-poker) with ZenHub @cazapatamar @danflop @erikasv @Trjegul84

**Comment by Trjegul84** [comment]
Se implementa el paso 1 del flujo (1.1 a 1.7). Se espera respuesta de Cristian por chat, porque aún no responde. Ya puede seguir con el paso 2.

**Comment by Trjegul84** [comment]
De esta tarea quedó pendiente el refinamiento y revisión de los comandos de los pasos 7.1 y 7.2

**Comment by erikasv** [comment]
Debido al cambio en la metodología para cargar los registros se cierra esta tarea
