### ISSUE TITLE
Documentar nuevo flujo de carga de registros

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-scrum#81]
- [x] Diagrama de flujo -> Erika
- [x] Instrucciones en gitlab (incluye el script que se debe ejecutar para cargar los registros de regreso a producción - recordar agregar el filtro por taxIDs) -> Camilo

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/81?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Se hizo una primera versión de la documentación en el gitlab y se socializa con @Trjegul84 en donde acordamos ir ajustando estas instrucciones a lo largo del proceso de carga de registros de mamiferos

**Comment by Trjegul84** [comment]
Para terminar la documentación del flujo, hace falta agregar el comando para clonar la colección solo con los registros determinados por la lista de taxIDs.

**Comment by erikasv** [comment]
Hola muchachos,

Algunos comentarios con respecto a la documentación del flujo:
- En el paso 1.2 las instrucciones son para la colección records pero en el comando tienen la colección especies (`-c species`).
- En el paso 1.7 la colección de records no va a coincidir, tal vez sería mejor dejar la aclaración temporalmente.
- En el paso 3.2.1, la primera vez tienen bien el nombre de la rama, la segunda y tercera vez la llaman `validación`, el nombre de la rama es `validation`.
- El paso 3.2.3 ya no aplica, las validaciones se ejecutan sobre la colección records.
- En el paso 3.2.6 no sugerir enviar la petición con `all` se demorará mucho e incluirá errores de registros adicionales a los de las especies que se están cargando
- Typo en el paso 3.2.7: `collecipon`
- El paso 5.2 es para los duplicados espaciales, no para la privacidad
- Paso 7.1: creo que ese comando no sirve para copiar la colección en la misma base de datos, así como está intentaría copiar la colección `records_tocopy` (en la versión anterior había una agregación para sacar la copia).
- Typo en [resptablecer](http://192.168.11.78/pem/biomodelos/tree/master/database/new_records#para-resptablecer-la-copia-de-los-registros-en-producci%C3%B3n-desde-una-carpeta-local) en utilidades.

**Comment by Trjegul84** [comment]
Arreglé las instrucciones y errores según las indicaciones de @erikasv 
Por favor revisar los ejemplos que puse en el punto 3.2.6 
Queda pendiente corregir el paso 7.2
