### ISSUE TITLE
Estrategia e implementación para copiar registros de pruebas a producción

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biomodelos-scrum#85]
Anteriormente se copiaba toda una colección de pruebas entre pruebas y producción. 

Lo que se busca es que ahora, por medio de un script externo o sentencias en mongo, se puedan copiar registros de una colección en pruebas, a una en producción.

**Comment by Trjegul84** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/85?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @erikasv

**Comment by cazapatamar** [comment]
Se realizó un script para ejecutar el mongo, el cual se encuentra en este [archivo](https://drive.google.com/file/d/1b-B2x6dW1dSYZCbXpIoI_vEJm5ylZk-L/view?usp=sharing) en el drive temporalmente pero que posteriormente será documentado en el gitlab junto con todo el flujo.

**Comment by cazapatamar** [comment]
@erikasv pensando lo que me sugeriste de incluir en el `find` la lista de los taxIDs, creo que no sería necesario ya que como lo tengo pensado, el flujo es asi:

- ....... pasos previos
- Teniendo la colección `records` en pruebas ya con todas las validaciones entonces desde ahí generar una nueva colección `records_murcielagos` con los taxIDs que se están subiendo. Ya tengo el comando para eso.
- Copiar esa coleccion `records_murcielagos` a producción como se hacía antes
- En este punto si ejecutar el script ya directamente estando el producción, el cual actualiza la colección `records` de producción.
- ....... pasos posteriores

Lo anterior lo pensé así para no tener que pasar toda la colección records de pruebas a producción teniendo en cuenta que solo nos interesan los taxIDs de murciélagos y esa colección puede ser muy grande.

Si te parece lo discutimos ahorita en la tarde.

**Comment by erikasv** [comment]
El problema es que la lista taxID no se tiene antes de iniciar la carga, porque entiendo que el script busca la especie y de ahí obtiene el taxID, y si no existe la crea, entonces no podríamos crear la otra colección para hacer la carga sino que se debe hacer directamente sobre `records`.

Una vez todo esté listo para ser llevado a producción sí podríamos crear la nueva colección (ahí se haría el filtro por taxID), copiar esa a la base de datos de producción y ejecutar el script sin tener que filtrar por taxID nuevamente

**Comment by erikasv** [comment]
Acabo de releer lo que describiste y es tal cual lo que dije, no sé por qué primero entendí que crearamos esta colección para cargar los nuevos registros :woman_facepalming: sorry :sweat_smile:
