### ISSUE TITLE
Spike: Revisar opciones para actualizar Recaptcha

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#86]
En BioModelos se está utilizando una gema que permite utilizar reCaptcha v2 de Google [https://www.google.com/recaptcha/about/](https://www.google.com/recaptcha/about/). Sin embargo, tenemos casos recurrentes donde se está logrando superar este servicio por parte de bots. Por esta razón, es necesario revisar opciones para continuar utilizando esta gema con una versión actualizada de reCaptcha u otras alternativas.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/86?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by alegnaaived** [comment]
Opciones identificadas:

1. [Usar reCaptcha v3 sin gemas](https://dev.to/morinoko/adding-recaptcha-v3-to-a-rails-app-without-a-gem-46jj)

1. [Acualizar configuración de la gema actual](https://github.com/ambethia/recaptcha#rails-installation)

[Tenemos la gema que tiene la última versión de reCaptcha](https://rubygems.org/gems/recaptcha/versions/5.8.1)

En el daily de hoy hablamos de revisar cuánto costaría la versión Enterprise vs. la versión que tenemos. https://cloud.google.com/recaptcha-enterprise/docs/compare-versions

Además se probará la versión 3 de reCaptcha en mi local

**Comment by alegnaaived** [comment]
Se probó reCaptcha v3 y se identificó que tiene el mismo comportamiento que la versión 2 porque [v2](https://github.com/ambethia/recaptcha#recaptcha_tags) y [v3](https://github.com/ambethia/recaptcha#recaptcha_v3) tienen TAGS diferentes y no los estamos usando.

Vista de BioModelos con v3:
![Captura de pantalla de 2021-11-26 15-14-32.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/a2ae5164-f253-422f-ac40-befba19e2567)

Vista de BioModelos con v2:
![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/94e839a0-ce2b-4fad-bbe4-f6a81460e58b)

Además, se revisó sobre los precios de [ReCaptcha Enterprise](https://cloud.google.com/recaptcha-enterprise/docs/overview) y son precios relacionados a funcionalidades y soporte para implementar 11 niveles de seguridad en lugar de los 4 niveles que tiene v3, y detección de filtración de contraseñas.

**Comment by alegnaaived** [comment]
La diferencia mencionada es que v3 necesita configurar tags y mapear la navegación del usuario en el sitio para determinar si es un robot. 

Se podría mejorar la implementación de reCaptcha v2 ([un ejemplo es este](https://www.thegreatcodeadventure.com/google-recaptcha-ruby/)) para validar el contenido de los campos.

[Datos sobre seguridad en Rails](https://guides.rubyonrails.org/v6.0/security.html)

**Comment by alegnaaived** [comment]
[Este es otro ejemplo](https://github.com/Shaher-11/udzilla/commit/8220527e79eb49fa045fe1d7d1593031524de5a0)

**Comment by alegnaaived** [comment]
También se podría actualizar la [configuración de variables de entorno](https://es.stackoverflow.com/questions/189790/como-generar-el-archivo-config-secrets-yml-en-rails/189845)

**Comment by alegnaaived** [comment]
Una alternativa a reCaptcha que se llama hCaptcha https://www.xataka.com/servicios/asi-hcaptcha-alternativa-a-recaptcha-google-que-dice-ser-privada-operar-15-internet
