### ISSUE TITLE
Diagnóstico usuarios BioModelos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#87]
Revisar y depurar los usuarios de BioModelos debido a la generación de usuarios falsos por parte de bots.

### Actualización 12-11-21
Crear un documento de excel en la carpeta de BioModelos para listar las propiedades de los usuarios considerados bots e incluir los usuarios repetidos.

Para todos los usuarios:
- id
- nombre de usuario
- email
- grupos a los que pertenece
- tareas asignadas
- modelos asociadas
- ediciones
- variables ecológicas
- Última fecha de login
- id del usuario repetido (no aplica para los bots)

**Comment by alegnaaived** [comment]
Se revisó la cantidad de usuarios en la base de datos y se identificaron 2008 usuarios.

Se realizó una revisión visual en los resultados de la consulta donde "sign_in_count =1 and organization is null" y se encontraron usuarios que se podrían eliminar o que se debe verificar si coincide con fechas de talleres y los participantes crearon usuarios no válidos. Se va a agregar toda esta información a una hoja de cálculo.

**Comment by alegnaaived** [comment]
@danflop, de estos usuarios, ¿cuáles estás de acuerdo que los eliminemos?

**Comment by alegnaaived** [comment]
[Enlace al archivo de revisión de usuarios](https://docs.google.com/spreadsheets/d/1bDiTXDIY2IhCXPbLl9ud3qpsS8M3UJPacrzT-l4uvxo/edit?usp=sharing). Los usuarios listados son aquellos que cumplen la condición "sign_in_count =1 and organization is null"
