### ISSUE TITLE
Crear bitacora para carga de registros

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#88]
### Descripción

El equipo de BioModelos desea saber el tiempo aproximado que toma la carga de registros cuando no se realiza con la prioridad de los talleres, ya que estos tiempos han variado en diferentes situaciones.

El objetivo es crear una hoja de cálculo donde se identifique cuando inició, cuándo finalizó, cuanto tiempo tomó (en días), qué tipo de carga fue (por ejemplo: reptiles, oso andino, etc).

### Consideraciones

- Verificar con Helena, que otra información sería importante registrar
- Crear la hoja de cálculo en la carpeta [carga de registros](https://drive.google.com/drive/folders/1brVODs13j17aqfL4wKeXou5DdVC8KbDY)

**Comment by alegnaaived** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/88?planning-poker) with ZenHub @cazapatamar @danflop @erikasv @Trjegul84
