### ISSUE TITLE
Documentar flujo de carga de modelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#92]
Documentar el flujo de carga de modelos en [este archivo](https://docs.google.com/document/d/14bMzzAa7WjGygTfHLPmU6gbe1NpLbqXQfkrOf80GTE4/edit?usp=sharing)

Tener en cuenta los detalles que puedan surgir durante la reunión con el equipo de biomodelos. Pero tener en cuenta el backup previo a la carga, que se realizará a demanda cuando se reciba la notificación de que el equipo de biomodelos va a iniciar el proceso de carga

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/92?planning-poker) with ZenHub @danflop @cazapatamar

**Comment by erikasv** [comment]
@cazapatamar yo lo veo bien, sólo ajusté unos cuantos typos. Cuando lo revises puedes pasar la tarea a `Done`

**Comment by cazapatamar** [comment]
Sólo adicioné lo del comando `bmdbutils setup`. De resto lo veo completo.
