### ISSUE TITLE
Levantar ambiente local con SSL

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biomodelos-scrum#94]
# Descripción

Levantar el ambiente local con SSL en contenedores (front, api, bases de datos y nginx).

**Comment by Trjegul84** [comment]
Se logró configurar el ambiente local con ssl. Se debe tener en cuenta que el puerto de la aplicación en el archivo de configuración de **nginx** debe ser el puerto del contenedor interno no el puerto expuesto en el host.
Si el mapeo de puertos del contenedor es por ejemplo: biomodelos-website-ssl  ` 3200:3000`  el archivo `default.conf` debería tener en la sección de _upstream_ una configuración como la siguiente:

```
upstream app {
    server biomodelos-website-ssl:3000;
}
```
