### ISSUE TITLE
Diagnosticar bug: Listado de usuarios que solicitan ingreso a un grupo no se actualizan y se encuentran duplicados

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biomodelos-scrum#99]
# Descripción

En este momento, cuando un usuario tipo moderador de un grupo revisa el listado de usuarios que han solicitado ingreso a un grupo y toma la decisión de aceptarlo, el listado no se actualiza y los sigue mostrando a pesar que el usuario efectivamente se convierte en un usuario miembro del grupo y aparece en los dos listados. Igualmente, existe un mismo usuario duplicado en el listado de pendientes.

Se busca que el listado se actualice en cuanto se tome una decisión por cada usuario haciendo clic en el botón correspondiente.

![image.png](https://images.zenhubusercontent.com/5898844951aa2c3057739338/7313a217-e556-4202-89fc-cfcc558819d0)

# Resultado
Identificar bien los casos en los que ocurre esto y determinar la razón de por qué pasa.

Adicionalmente se deben borrar las solicitudes duplicadas en producción, *después* de identificar el fallo internamente.

# Consideraciones
- Reproducirlo en desarrollo primero y verificar si es una regla general en el esquema de la base de datos.
- Podría estar sucediendo lo mismo en el caso de las especies. Probar este caso.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biomodelos-scrum/99?planning-poker) with ZenHub @cazapatamar @danflop @ManuelStardust @Trjegul84

**Comment by cazapatamar** [comment]
En al ambiente de producciòn no se puede replicar el comportamiento ya que al intentar asociar un usuario a un grupo aparece un error:

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/3b9c6bf0-55d8-4c1b-b60f-1d5be94b8efd)

Entonces se hacen pruebas en el ambiente de produccion con mi usuario en donde no se encontraron comportamientos extraños relacionados con la vinculacion a un grupo por parte de un usuario registrado. Se siguen estos pasos:

1. Se inicia sesión con el usuario
2. Se solicita unirse al grupo de aves (muñequito con el signo +)
![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/878ea7ac-a71c-4b76-9833-9ae30d59059b)
3. El icono cambia y ahora sale el mensaje "En espera de aprobación"
4. Se inicia sesiòn con el usuario moderaror Biomodelos
5. Se va al grupo de aves en donde aparece la solicitud realizara por el mi usuario y donde se muestra la opcion de aprobar y cancelar.
groups_users
6. Se aprueba la solicitud y ya el usuario aparece en el listado de expertos del grupo
![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/6a8e6c14-8fd3-48d3-aeb0-8ed75eaa00f5)

En conclusiòn, el flujo básico se está cumpliendo y no se identifican anomalias desde el punto de vista funcional.

**Comment by cazapatamar** [comment]
Por otro lado, y de acuerdo a lo que se identificó la semana pasada durante el taller en Popayán, se encontró que las solicitudes que estaban "pegadas" correspondian a usuarios que ya estaban en el grupo como expertos, es decir, habia mas de un registro en la tabla `groups_users` para ese grupo y usuario por lo que al intentar aprobar o rechazar el sistema no sabía que hacer dado que ya existia un registro guardado.

Estas solicitudes repetidas fueron borradas manualmente en la base de datos.

Cabe mencionar que la semana pasada igualmente se hizo la prueba con un usuario (Gabriel) que no estaba asociado al grupo de aves y se aprobo su solicitud por medio del usuario biomodelos y todo funcionó bien.

**Comment by cazapatamar** [comment]
Actualmente en el ambiente de produccion solo se encuentran 4 solicitudes repetidas en la tabla `groups_users`. 1 para el grupo `Peces dulceacuícolas` y 3 para el grupo `Flora de Páramo y Bosques Altoandino`.

Por el momento se dejan por si son utiles para identificar el problema de fondo pero si consideran que se deben borrar por fa me lo hacen saber @danflop . En el chat interno envío los datos puntuales ya que logro identificar algo extraño con las fechas de creacion y actualizacion de esos registros.

**Comment by cazapatamar** [comment]
Actualmente en el ambiente de produccion solo se encuentran 4 solicitudes repetidas en la tabla `groups_users`. 1 para el grupo `Peces dulceacuícolas` y 3 para el grupo `Flora de Páramo y Bosques Altoandino`.

Por el momento se dejan por si son utiles para identificar el problema de fondo pero si consideran que se deben borrar por fa me lo hacen saber @danflop . En el chat interno envío los datos puntuales ya que logro identificar algo extraño con las fechas de creacion y actualizacion de esos registros.

**Comment by cazapatamar** [comment]
Finalmente, se revisa la PK en la tabla `groups_users` y se identifica que esta está asociada al campo `id` el cual es una secuencia. Es decir, no existe PK compuesta para esta tabla por lo que esa restricción no se encuentra a nivel de la bd.
